stages:
  - build
  - test
  - deploy
  - validate

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  CS_IMAGE: $IMAGE_TAG

.deploy:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - chmod 400 "$SSH_PRIVATE_KEY"
    - ssh-add "$SSH_PRIVATE_KEY"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - cp "$SSH_KNOWN_HOSTS" ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  tags:
    - dind

test:
  stage: test
  image: python:3.14
  before_script:
    - curl -LsSf https://astral.sh/uv/install.sh | sh
    - source $HOME/.local/bin/env
    - uv sync --extra test --locked
  script:
    - uv run pytest

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Container-Scanning.gitlab-ci.yml
  - template: Jobs/SAST-IaC.gitlab-ci.yml

deploy:
  image: ubuntu
  stage: deploy
  extends: .deploy
  script:
    - ssh "$SSH_USER"@"$SSH_SERVER" "docker stop blaue_tonne_api || echo \"stop faild!\""
    - ssh "$SSH_USER"@"$SSH_SERVER" "docker rm blaue_tonne_api || echo \"rm faild!\""
    - ssh "$SSH_USER"@"$SSH_SERVER" "docker pull $CI_REGISTRY_IMAGE:latest"
    - ssh "$SSH_USER"@"$SSH_SERVER" "docker run --name blaue_tonne_api -d --restart always -p 8245:80 $CI_REGISTRY_IMAGE:latest"
  environment:
    name: production
    on_stop: undeploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual

undeploy:
  image: ubuntu
  stage: deploy
  extends: .deploy
  variables:
    GIT_STRATEGY: none
  script:
    - ssh "$SSH_USER"@"$SSH_SERVER" "docker stop blaue_tonne_api && docker rm blaue_tonne_api"
  environment:
    name: production
    action: stop
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  allow_failure: true

validate_deployment:
  stage: validate
  image: curlimages/curl:latest
  variables:
    GIT_STRATEGY: none
  script:
    - sleep 10
    - curl -fsL blauetonne.stkn.org/health
  allow_failure: false
  needs: ["deploy"]
