[project]
name = "blaue-tonne-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "camelot-py>=1.0.0",
    "fastapi[standard]>=0.115.8",
    "python-dateutil>=2.9.0.post0",
]
